[package]
name = "cocogitto_github_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
conventional_commit_parser = "0.9.3"
rocket = { version = "0.5.0-rc.1", features = ["json"] }
octocrab = "0.13.0"
async-trait = "0.1.51"
indoc = "1.0.3"
anyhow = "1.0.47"

[dev-dependencies]
tokio-test = "0.4.2"
