[package]
name = "cocogitto_github_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
conventional_commit_parser = "0.9.2"
rocket = { version = "0.5.0-rc.1", features = ["json"] }
chrono = { version = "0.4.19", features = ["serde"] }
octocrab = "0.13.0"
jsonwebtoken = "7"
tokio = "1.14.0"

[dev-dependencies]
tokio-test = "0.4.2"