address = "0.0.0.0"
port = 8080
github_private_key = """
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAnmw3zvBrhIdp6zcK2Z93sPch8kzMdR+z6Ckcszj3rpwvNA3U
27Eahxq4In7SmWvJXFSgZ+SpworqIHbp1AQyLNRK85ih9VTSjoYQkODnk9Oebfwh
wQWvyf928zbUE4D/J8WxMElRhDwV/r9XiHZUAlF2otFIwUMWl/JA8+X9agmt4NhD
GUTC5EMe+sZcPKH/9LrSeEmJSpPypuAhVlbEH0L49i3Zzf/MVCAwGSqCi2Y0C0p0
dZYFXJCLHMIQUNhIxlhu2qHclz9MTBobB7B/prj5rwsC9+0HGAjcGJ3Z5DQl7Mzm
q3fwLxeo5z8g8y8XGIF4kvqjn8yBQ8cRXf1gjwIDAQABAoIBAD5fCNHWYd45mf/b
GdB4Mh1gDuNgTRbHtoLuvLfq88ixAPyTfXxJC9KpOFmMaMmyYAKT5ttAcX2AR5Ek
gAbS6BYyNpgVPZ5jGMq4CYmgokvXAwb2PyvJW15Bz8kNiw1qugokkRAbrZZMObSk
DIhTXdvTystrbiN4kEqeO+hKYiz+p/fXVvLg0Qva5XnipdUOPmktlPncUM0v3l5h
LuOhMt//W8yHwWwZRGQBiw/4CcbhfrXEEV+BEW0Fc3znqkVKea+xgQ1ud2OnGYsM
fE403K6ZvTAddv9BBddUnrDHpLy/+ksCUPL3blINuiH/Rtv+9EAieUbVnsLSh8gi
SMX5RBECgYEAzMAbOO3VCNa4x5wkmbLoIVfrco7QfzyINVtZpYXYT3S0G+bDoGRl
nKre1a6RSZmP+p0cF8lmxRk2x5Hzy8mauv7cpk7ahGthmUF7eVSG7okUhd4ZnAmD
Vvle8XS8XJechk0WI1wgXhZe6CqiNd3+6KtSa6HEFSgBTtvb0taGtBUCgYEAxhOM
p1PR89SM954M25BA+Ammu9okECvsZCfpLBhn2VwYR/9dtBsYSUlF91K8Xh9EAJEE
uB2GnMWxgaN/1baPQmRz+j6XsTUl26jUuzEY1H1SvUIVbTwAHC79hEYeCVmkZHDl
sWsUVBI2a1+Dc1/mijsw5t6cZaAztMpciov3txMCgYBhO/3xjCi2WNpJmSJch3Tr
mMgskBv9wK5iwG4TSDvQh/ico3tVqTgELbVDPvKqRC328zOLLE8M3QuBvRNNPQGp
Oi1pIVtutVwVHt7XYMfvcdP4OuBolK/11tk6y5hEVI+1y9fulOqeI/uQP+bms/VB
Y1Lx4FGxRl1QqOJ8/vnbfQKBgGgceG6u6Qj/bITuhxWVEgENmZzdgN0bKSpPrAio
X1VpSb32JLt5Dl/e6q6fxzC1wFmH3/IiWtHmO3HHjXa4eT5NbIRZCAR1ygtWB1LI
8KMnqCigJoD+65Pkww4WiM0jV/wPNzv0639w/zeawY4QFy4LBJ4k3hGwjdz2DIQq
I68PAoGBAKRUOMDl7Z2J/c9xR0w4B1SDpUIf/svYVhPuDZp2z86y2Pnm7WfalB5A
zXhk4fIc0IrZnKTSMfc54X0Fkz853nWwwmsiGwy6RoUNPNzodlaxdvet54NpMSgN
Yf3XSH7xvB5WX44tu8FcD42qp3f6TxgDwi40++J2RmSuac2Rsj4m
-----END RSA PRIVATE KEY-----
"""