use serde::Deserialize;

use crate::model::installation::Installation;

#[derive(Debug, Deserialize)]
pub struct PullRequestEvent {
    pub action: PullRequestAction,
    pub number: u64,
    pub repository: PullRequestRepository,
    pub installation: Installation,
    pub pull_request: PullRequestEventInner,
}

#[derive(Debug, Deserialize)]
pub struct PullRequestEventInner {
    pub head: Head,
}

#[derive(Debug, Deserialize)]
pub struct Head {
    pub sha: String,
}

#[derive(Debug, Deserialize, Eq, PartialOrd, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum PullRequestAction {
    Synchronize,
    Opened,
    Closed,
}

#[derive(Debug, Deserialize)]
pub struct PullRequestRepository {
    pub name: String,
    pub owner: PullRequestOwner,
    pub default_branch: String,
}

#[derive(Debug, Deserialize)]
pub struct PullRequestOwner {
    pub login: String,
}

#[cfg(test)]
mod test {
    use crate::model::github_event::pull_request_event::PullRequestEvent;
    use indoc::indoc;

    const CHECK_SUITE_PAYLOAD: &str = indoc! {
        r#"
{
  "action": "requested",
  "check_suite": {
    "id": 18496347518,
    "node_id": "CS_kwDOIA5t-88AAAAETnfdfg",
    "head_branch": "main",
    "head_sha": "845bfb824341d5ceb485642a5355a5086202f926",
    "status": "queued",
    "conclusion": null,
    "url": "https://api.github.com/repos/abougouffa/minemacs/check-suites/18496347518",
    "before": "dd5c2a0f78afca2ca41699c6b72a7184e15db592",
    "after": "845bfb824341d5ceb485642a5355a5086202f926",
    "pull_requests": [

    ],
    "app": {
      "id": 151884,
      "slug": "cocogitto-bot",
      "node_id": "A_kwHOBZegJc4AAlFM",
      "owner": {
        "login": "cocogitto",
        "id": 93823013,
        "node_id": "O_kgDOBZegJQ",
        "avatar_url": "https://avatars.githubusercontent.com/u/93823013?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/cocogitto",
        "html_url": "https://github.com/cocogitto",
        "followers_url": "https://api.github.com/users/cocogitto/followers",
        "following_url": "https://api.github.com/users/cocogitto/following{/other_user}",
        "gists_url": "https://api.github.com/users/cocogitto/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/cocogitto/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/cocogitto/subscriptions",
        "organizations_url": "https://api.github.com/users/cocogitto/orgs",
        "repos_url": "https://api.github.com/users/cocogitto/repos",
        "events_url": "https://api.github.com/users/cocogitto/events{/privacy}",
        "received_events_url": "https://api.github.com/users/cocogitto/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "name": "Cocogitto-bot",
      "description": "[Cocogitto](https://github.com/cocogitto/cocogitto) is a set of cli tools for the [conventional commits specification](https://www.conventionalcommits.org/en/v1.0.0/). \r\n\r\nThis bot uses cocogitto to perform [status checks](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks) on your pull-requests and ensure every commit match the specification. \r\n\r\nOn failure, your pull-request will be decorated with a comment explaining what went wrong regarding the specification : \r\n\r\n![example screenshot](https://docs.cocogitto.io/cog-bot-example.png)\r\n ",
      "external_url": "https://docs.cocogitto.io",
      "html_url": "https://github.com/apps/cocogitto-bot",
      "created_at": "2021-11-15T12:20:09Z",
      "updated_at": "2021-12-10T08:50:56Z",
      "permissions": {
        "checks": "write",
        "contents": "read",
        "issues": "write",
        "metadata": "read",
        "pull_requests": "write",
        "statuses": "write"
      },
      "events": [
        "merge_queue_entry",
        "pull_request",
        "push",
        "status"
      ]
    },
    "created_at": "2023-11-26T01:23:30Z",
    "updated_at": "2023-11-26T01:23:30Z",
    "rerequestable": true,
    "runs_rerequestable": true,
    "latest_check_runs_count": 0,
    "check_runs_url": "https://api.github.com/repos/abougouffa/minemacs/check-suites/18496347518/check-runs",
    "head_commit": {
      "id": "845bfb824341d5ceb485642a5355a5086202f926",
      "tree_id": "e1c2fd565ccb174c9c36d1d04d4e9f06b21a0132",
      "message": "tweak(consult): bind `grep`/`file` alongside with `rg`/`fd`",
      "timestamp": "2023-11-26T01:22:42Z",
      "author": {
        "name": "Abdelhak Bougouffa",
        "email": "abougouffa@fedoraproject.org"
      },
      "committer": {
        "name": "Abdelhak Bougouffa",
        "email": "abougouffa@fedoraproject.org"
      }
    }
  },
  "repository": {
    "id": 537816571,
    "node_id": "R_kgDOIA5t-w",
    "name": "minemacs",
    "full_name": "abougouffa/minemacs",
    "private": false,
    "owner": {
      "login": "abougouffa",
      "id": 3716399,
      "node_id": "MDQ6VXNlcjM3MTYzOTk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3716399?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/abougouffa",
      "html_url": "https://github.com/abougouffa",
      "followers_url": "https://api.github.com/users/abougouffa/followers",
      "following_url": "https://api.github.com/users/abougouffa/following{/other_user}",
      "gists_url": "https://api.github.com/users/abougouffa/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/abougouffa/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/abougouffa/subscriptions",
      "organizations_url": "https://api.github.com/users/abougouffa/orgs",
      "repos_url": "https://api.github.com/users/abougouffa/repos",
      "events_url": "https://api.github.com/users/abougouffa/events{/privacy}",
      "received_events_url": "https://api.github.com/users/abougouffa/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/abougouffa/minemacs",
    "description": "MinEmacs: a minimal Emacs configuration framework for daily use",
    "fork": false,
    "url": "https://api.github.com/repos/abougouffa/minemacs",
    "forks_url": "https://api.github.com/repos/abougouffa/minemacs/forks",
    "keys_url": "https://api.github.com/repos/abougouffa/minemacs/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/abougouffa/minemacs/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/abougouffa/minemacs/teams",
    "hooks_url": "https://api.github.com/repos/abougouffa/minemacs/hooks",
    "issue_events_url": "https://api.github.com/repos/abougouffa/minemacs/issues/events{/number}",
    "events_url": "https://api.github.com/repos/abougouffa/minemacs/events",
    "assignees_url": "https://api.github.com/repos/abougouffa/minemacs/assignees{/user}",
    "branches_url": "https://api.github.com/repos/abougouffa/minemacs/branches{/branch}",
    "tags_url": "https://api.github.com/repos/abougouffa/minemacs/tags",
    "blobs_url": "https://api.github.com/repos/abougouffa/minemacs/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/abougouffa/minemacs/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/abougouffa/minemacs/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/abougouffa/minemacs/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/abougouffa/minemacs/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/abougouffa/minemacs/languages",
    "stargazers_url": "https://api.github.com/repos/abougouffa/minemacs/stargazers",
    "contributors_url": "https://api.github.com/repos/abougouffa/minemacs/contributors",
    "subscribers_url": "https://api.github.com/repos/abougouffa/minemacs/subscribers",
    "subscription_url": "https://api.github.com/repos/abougouffa/minemacs/subscription",
    "commits_url": "https://api.github.com/repos/abougouffa/minemacs/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/abougouffa/minemacs/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/abougouffa/minemacs/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/abougouffa/minemacs/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/abougouffa/minemacs/contents/{+path}",
    "compare_url": "https://api.github.com/repos/abougouffa/minemacs/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/abougouffa/minemacs/merges",
    "archive_url": "https://api.github.com/repos/abougouffa/minemacs/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/abougouffa/minemacs/downloads",
    "issues_url": "https://api.github.com/repos/abougouffa/minemacs/issues{/number}",
    "pulls_url": "https://api.github.com/repos/abougouffa/minemacs/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/abougouffa/minemacs/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/abougouffa/minemacs/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/abougouffa/minemacs/labels{/name}",
    "releases_url": "https://api.github.com/repos/abougouffa/minemacs/releases{/id}",
    "deployments_url": "https://api.github.com/repos/abougouffa/minemacs/deployments",
    "created_at": "2022-09-17T13:27:16Z",
    "updated_at": "2023-11-21T12:51:25Z",
    "pushed_at": "2023-11-26T01:23:28Z",
    "git_url": "git://github.com/abougouffa/minemacs.git",
    "ssh_url": "git@github.com:abougouffa/minemacs.git",
    "clone_url": "https://github.com/abougouffa/minemacs.git",
    "svn_url": "https://github.com/abougouffa/minemacs",
    "homepage": "https://abougouffa.github.io/minemacs/",
    "size": 4501,
    "stargazers_count": 88,
    "watchers_count": 88,
    "language": "Emacs Lisp",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "has_discussions": true,
    "forks_count": 10,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc6TGljZW5zZTEz"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "editor",
      "emacs",
      "email-client",
      "embedded-development",
      "feed-reader",
      "ide",
      "note-taking",
      "robotics-programming",
      "scientific-computing",
      "workflow",
      "writing-system"
    ],
    "visibility": "public",
    "forks": 10,
    "open_issues": 0,
    "watchers": 88,
    "default_branch": "main"
  },
  "sender": {
    "login": "abougouffa",
    "id": 3716399,
    "node_id": "MDQ6VXNlcjM3MTYzOTk=",
    "avatar_url": "https://avatars.githubusercontent.com/u/3716399?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/abougouffa",
    "html_url": "https://github.com/abougouffa",
    "followers_url": "https://api.github.com/users/abougouffa/followers",
    "following_url": "https://api.github.com/users/abougouffa/following{/other_user}",
    "gists_url": "https://api.github.com/users/abougouffa/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/abougouffa/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/abougouffa/subscriptions",
    "organizations_url": "https://api.github.com/users/abougouffa/orgs",
    "repos_url": "https://api.github.com/users/abougouffa/repos",
    "events_url": "https://api.github.com/users/abougouffa/events{/privacy}",
    "received_events_url": "https://api.github.com/users/abougouffa/received_events",
    "type": "User",
    "site_admin": false
  },
  "installation": {
    "id": 35471408,
    "node_id": "MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uMzU0NzE0MDg="
  }
}"#
    };

    #[test]
    fn test() {
        let _event: PullRequestEvent = serde_json::from_str(CHECK_SUITE_PAYLOAD).unwrap();
    }

    const PULL_REQUEST_OPENED_PAYLOAD: &str = r#"
{
  "action": "opened",
  "number": 19,
  "pull_request": {
    "url": "https://api.github.com/repos/cocogitto/cocogitto-bot/pulls/19",
    "id": 1616653405,
    "node_id": "PR_kwDOGZ8kfs5gXCxd",
    "html_url": "https://github.com/cocogitto/cocogitto-bot/pull/19",
    "diff_url": "https://github.com/cocogitto/cocogitto-bot/pull/19.diff",
    "patch_url": "https://github.com/cocogitto/cocogitto-bot/pull/19.patch",
    "issue_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/issues/19",
    "number": 19,
    "state": "open",
    "locked": false,
    "title": "refactor/migrate to axum",
    "user": {
      "login": "oknozor",
      "id": 24563836,
      "node_id": "MDQ6VXNlcjI0NTYzODM2",
      "avatar_url": "https://avatars.githubusercontent.com/u/24563836?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/oknozor",
      "html_url": "https://github.com/oknozor",
      "followers_url": "https://api.github.com/users/oknozor/followers",
      "following_url": "https://api.github.com/users/oknozor/following{/other_user}",
      "gists_url": "https://api.github.com/users/oknozor/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/oknozor/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/oknozor/subscriptions",
      "organizations_url": "https://api.github.com/users/oknozor/orgs",
      "repos_url": "https://api.github.com/users/oknozor/repos",
      "events_url": "https://api.github.com/users/oknozor/events{/privacy}",
      "received_events_url": "https://api.github.com/users/oknozor/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": null,
    "created_at": "2023-11-25T17:10:40Z",
    "updated_at": "2023-11-25T17:10:40Z",
    "closed_at": null,
    "merged_at": null,
    "merge_commit_sha": null,
    "assignee": null,
    "assignees": [

    ],
    "requested_reviewers": [

    ],
    "requested_teams": [

    ],
    "labels": [

    ],
    "milestone": null,
    "draft": true,
    "commits_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/pulls/19/commits",
    "review_comments_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/pulls/19/comments",
    "review_comment_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/pulls/comments{/number}",
    "comments_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/issues/19/comments",
    "statuses_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/statuses/749cb241a263ecc83152c1346c9e6be4dc9cb7e3",
    "head": {
      "label": "cocogitto:refactor/axum",
      "ref": "refactor/axum",
      "sha": "749cb241a263ecc83152c1346c9e6be4dc9cb7e3",
      "user": {
        "login": "cocogitto",
        "id": 93823013,
        "node_id": "O_kgDOBZegJQ",
        "avatar_url": "https://avatars.githubusercontent.com/u/93823013?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/cocogitto",
        "html_url": "https://github.com/cocogitto",
        "followers_url": "https://api.github.com/users/cocogitto/followers",
        "following_url": "https://api.github.com/users/cocogitto/following{/other_user}",
        "gists_url": "https://api.github.com/users/cocogitto/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/cocogitto/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/cocogitto/subscriptions",
        "organizations_url": "https://api.github.com/users/cocogitto/orgs",
        "repos_url": "https://api.github.com/users/cocogitto/repos",
        "events_url": "https://api.github.com/users/cocogitto/events{/privacy}",
        "received_events_url": "https://api.github.com/users/cocogitto/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "repo": {
        "id": 429859966,
        "node_id": "R_kgDOGZ8kfg",
        "name": "cocogitto-bot",
        "full_name": "cocogitto/cocogitto-bot",
        "private": false,
        "owner": {
          "login": "cocogitto",
          "id": 93823013,
          "node_id": "O_kgDOBZegJQ",
          "avatar_url": "https://avatars.githubusercontent.com/u/93823013?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/cocogitto",
          "html_url": "https://github.com/cocogitto",
          "followers_url": "https://api.github.com/users/cocogitto/followers",
          "following_url": "https://api.github.com/users/cocogitto/following{/other_user}",
          "gists_url": "https://api.github.com/users/cocogitto/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/cocogitto/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/cocogitto/subscriptions",
          "organizations_url": "https://api.github.com/users/cocogitto/orgs",
          "repos_url": "https://api.github.com/users/cocogitto/repos",
          "events_url": "https://api.github.com/users/cocogitto/events{/privacy}",
          "received_events_url": "https://api.github.com/users/cocogitto/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/cocogitto/cocogitto-bot",
        "description": "A pedantic conventional commit github bot powered by cocogitto",
        "fork": false,
        "url": "https://api.github.com/repos/cocogitto/cocogitto-bot",
        "forks_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/forks",
        "keys_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/teams",
        "hooks_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/hooks",
        "issue_events_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/issues/events{/number}",
        "events_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/events",
        "assignees_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/assignees{/user}",
        "branches_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/branches{/branch}",
        "tags_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/tags",
        "blobs_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/languages",
        "stargazers_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/stargazers",
        "contributors_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/contributors",
        "subscribers_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/subscribers",
        "subscription_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/subscription",
        "commits_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/contents/{+path}",
        "compare_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/merges",
        "archive_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/downloads",
        "issues_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/issues{/number}",
        "pulls_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/labels{/name}",
        "releases_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/releases{/id}",
        "deployments_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/deployments",
        "created_at": "2021-11-19T16:13:40Z",
        "updated_at": "2023-08-08T02:51:05Z",
        "pushed_at": "2023-11-25T17:10:41Z",
        "git_url": "git://github.com/cocogitto/cocogitto-bot.git",
        "ssh_url": "git@github.com:cocogitto/cocogitto-bot.git",
        "clone_url": "https://github.com/cocogitto/cocogitto-bot.git",
        "svn_url": "https://github.com/cocogitto/cocogitto-bot",
        "homepage": null,
        "size": 188,
        "stargazers_count": 3,
        "watchers_count": 3,
        "language": "Rust",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 1,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 10,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "bot",
          "commitlint",
          "conventional-commits"
        ],
        "visibility": "public",
        "forks": 1,
        "open_issues": 10,
        "watchers": 3,
        "default_branch": "main",
        "allow_squash_merge": true,
        "allow_merge_commit": false,
        "allow_rebase_merge": true,
        "allow_auto_merge": false,
        "delete_branch_on_merge": false,
        "allow_update_branch": false,
        "use_squash_pr_title_as_default": false,
        "squash_merge_commit_message": "COMMIT_MESSAGES",
        "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
        "merge_commit_message": "PR_TITLE",
        "merge_commit_title": "MERGE_MESSAGE"
      }
    },
    "base": {
      "label": "cocogitto:main",
      "ref": "main",
      "sha": "a71dada3f72c2fcf48e876f079e986ec0881caa9",
      "user": {
        "login": "cocogitto",
        "id": 93823013,
        "node_id": "O_kgDOBZegJQ",
        "avatar_url": "https://avatars.githubusercontent.com/u/93823013?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/cocogitto",
        "html_url": "https://github.com/cocogitto",
        "followers_url": "https://api.github.com/users/cocogitto/followers",
        "following_url": "https://api.github.com/users/cocogitto/following{/other_user}",
        "gists_url": "https://api.github.com/users/cocogitto/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/cocogitto/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/cocogitto/subscriptions",
        "organizations_url": "https://api.github.com/users/cocogitto/orgs",
        "repos_url": "https://api.github.com/users/cocogitto/repos",
        "events_url": "https://api.github.com/users/cocogitto/events{/privacy}",
        "received_events_url": "https://api.github.com/users/cocogitto/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "repo": {
        "id": 429859966,
        "node_id": "R_kgDOGZ8kfg",
        "name": "cocogitto-bot",
        "full_name": "cocogitto/cocogitto-bot",
        "private": false,
        "owner": {
          "login": "cocogitto",
          "id": 93823013,
          "node_id": "O_kgDOBZegJQ",
          "avatar_url": "https://avatars.githubusercontent.com/u/93823013?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/cocogitto",
          "html_url": "https://github.com/cocogitto",
          "followers_url": "https://api.github.com/users/cocogitto/followers",
          "following_url": "https://api.github.com/users/cocogitto/following{/other_user}",
          "gists_url": "https://api.github.com/users/cocogitto/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/cocogitto/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/cocogitto/subscriptions",
          "organizations_url": "https://api.github.com/users/cocogitto/orgs",
          "repos_url": "https://api.github.com/users/cocogitto/repos",
          "events_url": "https://api.github.com/users/cocogitto/events{/privacy}",
          "received_events_url": "https://api.github.com/users/cocogitto/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/cocogitto/cocogitto-bot",
        "description": "A pedantic conventional commit github bot powered by cocogitto",
        "fork": false,
        "url": "https://api.github.com/repos/cocogitto/cocogitto-bot",
        "forks_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/forks",
        "keys_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/teams",
        "hooks_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/hooks",
        "issue_events_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/issues/events{/number}",
        "events_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/events",
        "assignees_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/assignees{/user}",
        "branches_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/branches{/branch}",
        "tags_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/tags",
        "blobs_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/languages",
        "stargazers_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/stargazers",
        "contributors_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/contributors",
        "subscribers_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/subscribers",
        "subscription_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/subscription",
        "commits_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/contents/{+path}",
        "compare_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/merges",
        "archive_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/downloads",
        "issues_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/issues{/number}",
        "pulls_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/labels{/name}",
        "releases_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/releases{/id}",
        "deployments_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/deployments",
        "created_at": "2021-11-19T16:13:40Z",
        "updated_at": "2023-08-08T02:51:05Z",
        "pushed_at": "2023-11-25T17:10:41Z",
        "git_url": "git://github.com/cocogitto/cocogitto-bot.git",
        "ssh_url": "git@github.com:cocogitto/cocogitto-bot.git",
        "clone_url": "https://github.com/cocogitto/cocogitto-bot.git",
        "svn_url": "https://github.com/cocogitto/cocogitto-bot",
        "homepage": null,
        "size": 188,
        "stargazers_count": 3,
        "watchers_count": 3,
        "language": "Rust",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 1,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 10,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "bot",
          "commitlint",
          "conventional-commits"
        ],
        "visibility": "public",
        "forks": 1,
        "open_issues": 10,
        "watchers": 3,
        "default_branch": "main",
        "allow_squash_merge": true,
        "allow_merge_commit": false,
        "allow_rebase_merge": true,
        "allow_auto_merge": false,
        "delete_branch_on_merge": false,
        "allow_update_branch": false,
        "use_squash_pr_title_as_default": false,
        "squash_merge_commit_message": "COMMIT_MESSAGES",
        "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
        "merge_commit_message": "PR_TITLE",
        "merge_commit_title": "MERGE_MESSAGE"
      }
    },
    "_links": {
      "self": {
        "href": "https://api.github.com/repos/cocogitto/cocogitto-bot/pulls/19"
      },
      "html": {
        "href": "https://github.com/cocogitto/cocogitto-bot/pull/19"
      },
      "issue": {
        "href": "https://api.github.com/repos/cocogitto/cocogitto-bot/issues/19"
      },
      "comments": {
        "href": "https://api.github.com/repos/cocogitto/cocogitto-bot/issues/19/comments"
      },
      "review_comments": {
        "href": "https://api.github.com/repos/cocogitto/cocogitto-bot/pulls/19/comments"
      },
      "review_comment": {
        "href": "https://api.github.com/repos/cocogitto/cocogitto-bot/pulls/comments{/number}"
      },
      "commits": {
        "href": "https://api.github.com/repos/cocogitto/cocogitto-bot/pulls/19/commits"
      },
      "statuses": {
        "href": "https://api.github.com/repos/cocogitto/cocogitto-bot/statuses/749cb241a263ecc83152c1346c9e6be4dc9cb7e3"
      }
    },
    "author_association": "CONTRIBUTOR",
    "auto_merge": null,
    "active_lock_reason": null,
    "merged": false,
    "mergeable": null,
    "rebaseable": null,
    "mergeable_state": "unknown",
    "merged_by": null,
    "comments": 0,
    "review_comments": 0,
    "maintainer_can_modify": false,
    "commits": 1,
    "additions": 375,
    "deletions": 441,
    "changed_files": 12
  },
  "repository": {
    "id": 429859966,
    "node_id": "R_kgDOGZ8kfg",
    "name": "cocogitto-bot",
    "full_name": "cocogitto/cocogitto-bot",
    "private": false,
    "owner": {
      "login": "cocogitto",
      "id": 93823013,
      "node_id": "O_kgDOBZegJQ",
      "avatar_url": "https://avatars.githubusercontent.com/u/93823013?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cocogitto",
      "html_url": "https://github.com/cocogitto",
      "followers_url": "https://api.github.com/users/cocogitto/followers",
      "following_url": "https://api.github.com/users/cocogitto/following{/other_user}",
      "gists_url": "https://api.github.com/users/cocogitto/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cocogitto/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cocogitto/subscriptions",
      "organizations_url": "https://api.github.com/users/cocogitto/orgs",
      "repos_url": "https://api.github.com/users/cocogitto/repos",
      "events_url": "https://api.github.com/users/cocogitto/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cocogitto/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/cocogitto/cocogitto-bot",
    "description": "A pedantic conventional commit github bot powered by cocogitto",
    "fork": false,
    "url": "https://api.github.com/repos/cocogitto/cocogitto-bot",
    "forks_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/forks",
    "keys_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/teams",
    "hooks_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/hooks",
    "issue_events_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/issues/events{/number}",
    "events_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/events",
    "assignees_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/assignees{/user}",
    "branches_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/branches{/branch}",
    "tags_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/tags",
    "blobs_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/languages",
    "stargazers_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/stargazers",
    "contributors_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/contributors",
    "subscribers_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/subscribers",
    "subscription_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/subscription",
    "commits_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/contents/{+path}",
    "compare_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/merges",
    "archive_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/downloads",
    "issues_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/issues{/number}",
    "pulls_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/labels{/name}",
    "releases_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/releases{/id}",
    "deployments_url": "https://api.github.com/repos/cocogitto/cocogitto-bot/deployments",
    "created_at": "2021-11-19T16:13:40Z",
    "updated_at": "2023-08-08T02:51:05Z",
    "pushed_at": "2023-11-25T17:10:41Z",
    "git_url": "git://github.com/cocogitto/cocogitto-bot.git",
    "ssh_url": "git@github.com:cocogitto/cocogitto-bot.git",
    "clone_url": "https://github.com/cocogitto/cocogitto-bot.git",
    "svn_url": "https://github.com/cocogitto/cocogitto-bot",
    "homepage": null,
    "size": 188,
    "stargazers_count": 3,
    "watchers_count": 3,
    "language": "Rust",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 1,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 10,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "bot",
      "commitlint",
      "conventional-commits"
    ],
    "visibility": "public",
    "forks": 1,
    "open_issues": 10,
    "watchers": 3,
    "default_branch": "main",
    "custom_properties": {

    }
  },
  "organization": {
    "login": "cocogitto",
    "id": 93823013,
    "node_id": "O_kgDOBZegJQ",
    "url": "https://api.github.com/orgs/cocogitto",
    "repos_url": "https://api.github.com/orgs/cocogitto/repos",
    "events_url": "https://api.github.com/orgs/cocogitto/events",
    "hooks_url": "https://api.github.com/orgs/cocogitto/hooks",
    "issues_url": "https://api.github.com/orgs/cocogitto/issues",
    "members_url": "https://api.github.com/orgs/cocogitto/members{/member}",
    "public_members_url": "https://api.github.com/orgs/cocogitto/public_members{/member}",
    "avatar_url": "https://avatars.githubusercontent.com/u/93823013?v=4",
    "description": "The conventional commit toolbox"
  },
  "sender": {
    "login": "oknozor",
    "id": 24563836,
    "node_id": "MDQ6VXNlcjI0NTYzODM2",
    "avatar_url": "https://avatars.githubusercontent.com/u/24563836?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/oknozor",
    "html_url": "https://github.com/oknozor",
    "followers_url": "https://api.github.com/users/oknozor/followers",
    "following_url": "https://api.github.com/users/oknozor/following{/other_user}",
    "gists_url": "https://api.github.com/users/oknozor/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/oknozor/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/oknozor/subscriptions",
    "organizations_url": "https://api.github.com/users/oknozor/orgs",
    "repos_url": "https://api.github.com/users/oknozor/repos",
    "events_url": "https://api.github.com/users/oknozor/events{/privacy}",
    "received_events_url": "https://api.github.com/users/oknozor/received_events",
    "type": "User",
    "site_admin": false
  },
  "installation": {
    "id": 20719195,
    "node_id": "MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uMjA3MTkxOTU="
  }
}
"#;

    #[test]
    fn should_parse_pull_request_opened() {
        let _event: PullRequestEvent = serde_json::from_str(PULL_REQUEST_OPENED_PAYLOAD).unwrap();
    }
}
